# Generated by Django 4.1.4 on 2023-02-22 17:56

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='User',
            fields=[
                ('userID', models.CharField(max_length=4, primary_key=True, serialize=False)),
                ('userName', models.TextField()),
                ('password', models.TextField()),
            ],
        ),
    ]
