# Generated by Django 4.1.4 on 2023-02-23 14:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('stock', '0002_item'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='User',
            new_name='UserStaff',
        ),
    ]
