# Generated by Django 4.1.4 on 2023-02-23 16:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stock', '0003_rename_user_userstaff'),
    ]

    operations = [
        migrations.CreateModel(
            name='Product',
            fields=[
                ('productID', models.CharField(max_length=4, primary_key=True, serialize=False)),
                ('productName', models.TextField()),
                ('category', models.TextField()),
                ('price', models.DecimalField(decimal_places=2, max_digits=4)),
            ],
        ),
        migrations.RenameModel(
            old_name='UserStaff',
            new_name='Staff',
        ),
        migrations.DeleteModel(
            name='Item',
        ),
        migrations.RenameField(
            model_name='staff',
            old_name='userID',
            new_name='staffID',
        ),
        migrations.RenameField(
            model_name='staff',
            old_name='userName',
            new_name='staffName',
        ),
    ]
