# Generated by Django 4.1.4 on 2023-02-23 16:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stock', '0004_product_rename_userstaff_staff_delete_item_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Supplier',
            fields=[
                ('supplierID', models.CharField(max_length=4, primary_key=True, serialize=False)),
                ('supplierName', models.TextField()),
                ('email', models.TextField()),
            ],
        ),
    ]
