# Generated by Django 4.1.4 on 2023-02-23 23:33

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('stock', '0005_supplier'),
    ]

    operations = [
        migrations.CreateModel(
            name='TrackStock',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantity', models.IntegerField()),
                ('productID', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='stock.product')),
                ('supplierID', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='stock.supplier')),
            ],
        ),
    ]
