# Generated by Django 4.1.4 on 2023-02-24 03:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('stock', '0006_trackstock'),
    ]

    operations = [
        migrations.DeleteModel(
            name='TrackStock',
        ),
    ]
