# Generated by Django 4.1.4 on 2023-02-24 03:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stock', '0007_delete_trackstock'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='quantity',
            field=models.IntegerField(default=0),
        ),
    ]
