# Generated by Django 4.1.4 on 2023-02-24 03:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('stock', '0008_product_quantity'),
    ]

    operations = [
        migrations.RenameField(
            model_name='product',
            old_name='quantity',
            new_name='totalQuantity',
        ),
    ]
