# Generated by Django 4.1.4 on 2023-02-24 03:38

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('stock', '0009_rename_quantity_product_totalquantity'),
    ]

    operations = [
        migrations.CreateModel(
            name='StocksManagement',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField()),
                ('quantity', models.IntegerField()),
                ('status', models.CharField(max_length=3)),
                ('productID', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='stock.product')),
                ('staffID', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='stock.staff')),
            ],
        ),
    ]
