# Generated by Django 4.1.4 on 2023-02-24 07:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stock', '0010_stocksmanagement'),
    ]

    operations = [
        migrations.AlterField(
            model_name='stocksmanagement',
            name='date',
            field=models.DateField(null=True),
        ),
    ]
