# Generated by Django 4.1.4 on 2023-02-24 07:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stock', '0011_alter_stocksmanagement_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='stocksmanagement',
            name='quantity',
            field=models.IntegerField(null=True),
        ),
        migrations.AlterField(
            model_name='stocksmanagement',
            name='status',
            field=models.CharField(max_length=3, null=True),
        ),
    ]
