# Generated by Django 4.1.4 on 2023-02-24 07:06

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('stock', '0012_alter_stocksmanagement_quantity_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='stocksmanagement',
            name='productID',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='stock.product'),
        ),
        migrations.AlterField(
            model_name='stocksmanagement',
            name='staffID',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='stock.staff'),
        ),
    ]
