# Generated by Django 4.1.4 on 2023-02-26 04:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stock', '0014_alter_staff_password_alter_staff_staffname'),
    ]

    operations = [
        migrations.AlterField(
            model_name='staff',
            name='password',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='staff',
            name='staffName',
            field=models.TextField(blank=True, null=True),
        ),
    ]
