# Generated by Django 4.1.4 on 2023-02-27 07:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('stock', '0015_alter_staff_password_alter_staff_staffname'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Supplier',
        ),
    ]
