# Generated by Django 4.1.4 on 2023-02-27 07:48

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('stock', '0016_delete_supplier'),
    ]

    operations = [
        migrations.CreateModel(
            name='AskQuestion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('question', models.TextField()),
                ('answer', models.TextField()),
                ('staffID', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='stock.staff')),
            ],
        ),
    ]
