# Generated by Django 4.1.4 on 2023-02-27 07:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stock', '0018_alter_askquestion_answer'),
    ]

    operations = [
        migrations.AlterField(
            model_name='askquestion',
            name='answer',
            field=models.TextField(blank=True, null=True),
        ),
    ]
