# Generated by Django 4.1.4 on 2023-02-27 08:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('stock', '0019_alter_askquestion_answer'),
    ]

    operations = [
        migrations.DeleteModel(
            name='AskQuestion',
        ),
    ]
